
import { Patient, Scheme, SchemeRecommendation, User, Stats } from "@/types";

// Mock Users
export const users: User[] = [
  {
    id: "user1",
    name: "Dr. Jane Smith",
    email: "jane.smith@facility.com",
    role: "facility",
    facility: "City Hospital",
    hospital: "City Hospital",
    district: "Central",
    state: "State A",
    avatar: "/placeholder.svg",
  },
  {
    id: "user2",
    name: "Michael Johnson",
    email: "michael.johnson@hospital.com",
    role: "hospital",
    hospital: "City Hospital",
    district: "Central",
    state: "State A",
    avatar: "/placeholder.svg",
  },
  {
    id: "user3",
    name: "Amanda Lee",
    email: "amanda.lee@district.com",
    role: "district",
    district: "Central",
    state: "State A",
    avatar: "/placeholder.svg",
  },
  {
    id: "user4",
    name: "Robert Chen",
    email: "robert.chen@state.com",
    role: "state",
    state: "State A",
    avatar: "/placeholder.svg",
  },
  {
    id: "user5",
    name: "Sarah Williams",
    email: "sarah.williams@super.com",
    role: "super",
    avatar: "/placeholder.svg",
  },
];

// Mock Patients
export const patients: Patient[] = [
  {
    id: "patient1",
    name: "John Doe",
    age: 45,
    gender: "male",
    address: "123 Main St, Central District",
    contact: "555-123-4567",
    medicalHistory: "Hypertension, Diabetes",
    income: 150000,
    category: "general",
    insuranceStatus: false,
    createdAt: new Date("2023-01-15"),
    updatedBy: "user1",
  },
  {
    id: "patient2",
    name: "Mary Johnson",
    age: 60,
    gender: "female",
    address: "456 Oak Ave, Central District",
    contact: "555-234-5678",
    medicalHistory: "Arthritis",
    income: 75000,
    category: "obc",
    insuranceStatus: false,
    createdAt: new Date("2023-02-20"),
    updatedBy: "user1",
  },
  {
    id: "patient3",
    name: "Raj Patel",
    age: 30,
    gender: "male",
    address: "789 Pine St, Central District",
    contact: "555-345-6789",
    medicalHistory: "Asthma",
    income: 250000,
    category: "general",
    insuranceStatus: true,
    createdAt: new Date("2023-03-10"),
    updatedBy: "user1",
  },
  {
    id: "patient4",
    name: "Priya Singh",
    age: 25,
    gender: "female",
    address: "101 Elm St, Western District",
    contact: "555-456-7890",
    medicalHistory: "None",
    income: 120000,
    category: "sc",
    insuranceStatus: false,
    createdAt: new Date("2023-04-05"),
    updatedBy: "user1",
  },
  {
    id: "patient5",
    name: "David Kim",
    age: 50,
    gender: "male",
    address: "202 Maple Ave, Eastern District",
    contact: "555-567-8901",
    medicalHistory: "Cardiac Issues",
    income: 85000,
    category: "st",
    insuranceStatus: false,
    createdAt: new Date("2023-05-12"),
    updatedBy: "user1",
  },
];

// Mock Schemes
export const schemes: Scheme[] = [
  {
    id: "scheme1",
    name: "Health For All",
    description: "Universal health coverage for low-income families",
    eligibilityCriteria: {
      income: { max: 100000 },
      category: ["sc", "st", "obc"],
    },
    benefits: ["Free hospitalization", "Medicine subsidies", "Regular health checkups"],
    documents: ["Income Certificate", "Identity Proof", "Address Proof"],
  },
  {
    id: "scheme2",
    name: "Senior Care Plus",
    description: "Comprehensive healthcare for senior citizens",
    eligibilityCriteria: {
      age: { min: 60 },
    },
    benefits: ["Free hospitalization", "Specialized geriatric care", "Monthly pension"],
    documents: ["Age Certificate", "Identity Proof", "Medical History"],
  },
  {
    id: "scheme3",
    name: "Maternal Welfare Scheme",
    description: "Healthcare for pregnant women and new mothers",
    eligibilityCriteria: {
      gender: ["female"],
      age: { min: 18, max: 45 },
    },
    benefits: ["Free prenatal care", "Nutritional supplements", "Childbirth expenses"],
    documents: ["Pregnancy Confirmation", "Identity Proof", "Address Proof"],
  },
  {
    id: "scheme4",
    name: "Child Health Initiative",
    description: "Comprehensive healthcare for children",
    eligibilityCriteria: {
      age: { max: 18 },
    },
    benefits: ["Free vaccinations", "Nutritional support", "Pediatric consultations"],
    documents: ["Birth Certificate", "Identity Proof of Guardian", "School Enrollment (if applicable)"],
  },
  {
    id: "scheme5",
    name: "Universal Health Coverage",
    description: "Basic health coverage for all citizens",
    eligibilityCriteria: {},
    benefits: ["Basic health checkups", "Emergency care", "Disease prevention programs"],
    documents: ["Identity Proof", "Address Proof"],
  },
];

// Mock Scheme Recommendations
export const recommendations: SchemeRecommendation[] = [
  {
    id: "rec1",
    patientId: "patient2",
    schemeId: "scheme2",
    status: "hospital_approved",
    hospitalApprovedAt: new Date("2023-02-21"),
    comments: "Patient meets all criteria",
    createdAt: new Date("2023-02-20"),
    updatedAt: new Date("2023-02-21"),
  },
  {
    id: "rec2",
    patientId: "patient4",
    schemeId: "scheme1",
    status: "district_approved",
    hospitalApprovedAt: new Date("2023-04-06"),
    districtApprovedAt: new Date("2023-04-08"),
    comments: "Approved based on income and category",
    createdAt: new Date("2023-04-05"),
    updatedAt: new Date("2023-04-08"),
  },
  {
    id: "rec3",
    patientId: "patient5",
    schemeId: "scheme5",
    status: "suggested",
    comments: "Eligible for basic coverage",
    createdAt: new Date("2023-05-12"),
    updatedAt: new Date("2023-05-12"),
  },
  {
    id: "rec4",
    patientId: "patient3",
    schemeId: "scheme5",
    status: "rejected",
    comments: "Already has private insurance",
    createdAt: new Date("2023-03-10"),
    updatedAt: new Date("2023-03-15"),
  },
  {
    id: "rec5",
    patientId: "patient1",
    schemeId: "scheme1",
    status: "state_approved",
    hospitalApprovedAt: new Date("2023-01-16"),
    districtApprovedAt: new Date("2023-01-18"),
    stateApprovedAt: new Date("2023-01-20"),
    comments: "Fully approved for implementation",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-01-20"),
  },
];

// Mock Stats for various admin levels
export const statsMap: Record<string, Stats> = {
  hospital: {
    totalPatients: 150,
    totalRecommendations: 120,
    pendingApprovals: 25,
    approvedRecommendations: 85,
    rejectedRecommendations: 10,
  },
  district: {
    totalPatients: 850,
    totalRecommendations: 720,
    pendingApprovals: 150,
    approvedRecommendations: 520,
    rejectedRecommendations: 50,
  },
  state: {
    totalPatients: 5200,
    totalRecommendations: 4500,
    pendingApprovals: 800,
    approvedRecommendations: 3400,
    rejectedRecommendations: 300,
  },
  super: {
    totalPatients: 28000,
    totalRecommendations: 25000,
    pendingApprovals: 4000,
    approvedRecommendations: 19000,
    rejectedRecommendations: 2000,
  },
};
